-- 1. 상품 정보를 담는 테이블 생성
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  price_self INTEGER NOT NULL,
  price_family INTEGER NOT NULL,
  price_acquaintance INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. 5개 상품 기본 데이터 삽입 (초기화)
INSERT INTO public.products (name, price_self, price_family, price_acquaintance)
VALUES
  ('앰플런스 앰플 (50ml)', 6500, 9500, 13000),
  ('앰플런스 크림 (75ml)', 5000, 7000, 9000),
  ('앰플런스 버블폼 (150ml)', 5500, 9500, 10000),
  ('딥모이스처 카머(70ml)', 5000, 7000, 9000),
  ('인텐시브 베리어 카머 (90ml)', 6000, 8000, 10000)
ON CONFLICT DO NOTHING;
